server: "localhost"
port: "1433"
database: "TSQL2012"
table: "ORDERS"
user: "etl-usr"
password: "U3VwZXItZXRsLXVzZXI="
mongouri: "mongodb://localhost:27017"
databasemongo: "etl-test"
collection: "fact_orders"
batchsize: 50